declare const styles: {
  readonly cardGrid: string
  readonly cardGridColumn: string
  readonly cardGridColumnArrowHover: string
  readonly cardGridColumnDesktopStartDivider: string
  readonly cardGridColumnMiddleDesktopRow: string
  readonly cardGridColumnMiddleMobileRow: string
  readonly cardGridColumnMiddleTabletRow: string
  readonly cardGridColumnTabletDivider: string
  readonly cardGridFooterColumn: string
  readonly cardGridItem: string
  readonly featuredSection: string
  readonly hero: string
  readonly heroSection: string
  readonly layout: string
  readonly main: string
  readonly page: string
  readonly paginationFrame: string
  readonly redlineBackground: string
  readonly redlineBase: string
  readonly resourceCard: string
  readonly sectionHeader: string
  readonly sectionHeaderColumn: string
  readonly sectionHeaderWithSort: string
  readonly sectionSpacer: string
  readonly sidebar: string
  readonly sortLabel: string
}
export = styles
