declare const styles: {
  readonly "ai": string;
  readonly "collaboration": string;
  readonly "enterprise": string;
  readonly "featuredBentoContent": string;
  readonly "featuredBentoItem": string;
  readonly "featuredBentoVisual": string;
  readonly "footnoteInlineLink": string;
  readonly "footnoteSizeLarge": string;
  readonly "footnoteSizeSmall": string;
  readonly "heightFull": string;
  readonly "imageFillMedia": string;
  readonly "left": string;
  readonly "logoWrapper": string;
  readonly "normalizeMargin": string;
  readonly "normalizePadding": string;
  readonly "paddingBottom-condensed": string;
  readonly "paddingBottom-none": string;
  readonly "paddingBottom-normal": string;
  readonly "paddingBottom-spacious": string;
  readonly "productivity": string;
  readonly "right": string;
  readonly "riverBreakoutNoCta": string;
  readonly "section": string;
  readonly "sectionIntro": string;
  readonly "security": string;
  readonly "stackedItemHeading": string;
  readonly "stackedItemText": string;
  readonly "statistic": string;
  readonly "testimonialBackgroundImageShape": string;
  readonly "wrapper": string;
};
export = styles;

