/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: Grid', () => {
  test('Grid / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid--default&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Playground', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid--playground&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Asymmetry', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--asymmetry&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Nesting', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--nesting&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Responsive', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--responsive&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Centering', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--centering&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Ratio: 50:50', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--fifty-fifty&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Ratio: 60:40', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--sixty-forty&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Ratio: 40:60', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-grid-features--forty-sixty&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Responsive Min Width', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-grid-features--responsive-min-width&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Grid / Disable Gutters', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-grid-features--disable-gutters&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
