declare const styles: {
  readonly "ActionMenu": string;
  readonly "ActionMenu--disabled": string;
  readonly "ActionMenu__button": string;
  readonly "ActionMenu__button--default": string;
  readonly "ActionMenu__button--medium": string;
  readonly "ActionMenu__button--small": string;
  readonly "ActionMenu__button--split-button": string;
  readonly "ActionMenu__innerButton--disabled": string;
  readonly "ActionMenu__innerButton--split-button": string;
  readonly "ActionMenu__innerButton--subtle": string;
  readonly "ActionMenu__item": string;
  readonly "ActionMenu__item--medium": string;
  readonly "ActionMenu__item--selection-type-single": string;
  readonly "ActionMenu__item--small": string;
  readonly "ActionMenu__item-anchor": string;
  readonly "ActionMenu__item-anchor--disabled": string;
  readonly "ActionMenu__item-content--disabled": string;
  readonly "ActionMenu__item-icon": string;
  readonly "ActionMenu__item-icon--disabled": string;
  readonly "ActionMenu__item-leadingVisual": string;
  readonly "ActionMenu__item-text": string;
  readonly "ActionMenu__menu": string;
  readonly "ActionMenu__menu--medium": string;
  readonly "ActionMenu__menu--pos-outside-bottom": string;
  readonly "ActionMenu__menu--pos-outside-top": string;
  readonly "ActionMenu__menu--small": string;
  readonly "ActionMenu__menu--visible": string;
  readonly "overlay-appear-outside-bottom": string;
  readonly "overlay-appear-outside-top": string;
};
export = styles;

