/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: ActionMenu', () => {
  test('ActionMenu / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-actionmenu--default&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Default (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu--default&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Default (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu--default&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Default (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu--default&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Default (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu--default&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Default (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu--default&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--single-selection&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--single-selection&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--single-selection&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--single-selection&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--single-selection&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--single-selection&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection Small Open', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--single-selection-small-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection Small Open (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--single-selection-small-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection Small Open (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--single-selection-small-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection Small Open (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--single-selection-small-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection Small Open (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--single-selection-small-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Single Selection Small Open (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--single-selection-small-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--split-button-mode&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--split-button-mode&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--split-button-mode&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--split-button-mode&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--split-button-mode&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--split-button-mode&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Disabled', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--split-button-mode-disabled&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Disabled (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--split-button-mode-disabled&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Disabled (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--split-button-mode-disabled&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Disabled (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--split-button-mode-disabled&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Disabled (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--split-button-mode-disabled&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Disabled (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--split-button-mode-disabled&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Open', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--split-button-mode-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Open (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--split-button-mode-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Open (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--split-button-mode-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Open (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--split-button-mode-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Open (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--split-button-mode-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode Open (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--split-button-mode-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Alternative Menu Alignment', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--split-button-alternative-menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Alternative Menu Alignment (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--split-button-alternative-menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Alternative Menu Alignment (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--split-button-alternative-menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Alternative Menu Alignment (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--split-button-alternative-menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Alternative Menu Alignment (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--split-button-alternative-menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Alternative Menu Alignment (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--split-button-alternative-menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode All Variants', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--split-button-mode-all-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode All Variants (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--split-button-mode-all-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode All Variants (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--split-button-mode-all-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode All Variants (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--split-button-mode-all-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode All Variants (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--split-button-mode-all-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode All Variants (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--split-button-mode-all-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode In Hero', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--split-button-mode-in-hero&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode In Hero (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--split-button-mode-in-hero&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode In Hero (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--split-button-mode-in-hero&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode In Hero (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--split-button-mode-in-hero&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode In Hero (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--split-button-mode-in-hero&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Split Button Mode In Hero (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--split-button-mode-in-hero&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / In Stack', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--in-stack&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / In Stack (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--in-stack&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / In Stack (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--in-stack&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / In Stack (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--in-stack&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / In Stack (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--in-stack&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / In Stack (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--in-stack&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Sizes', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--sizes&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Sizes (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--sizes&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Sizes (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--sizes&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Sizes (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--sizes&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Sizes (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--sizes&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Sizes (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--sizes&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Open By Default', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--open-by-default&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Open By Default (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--open-by-default&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Open By Default (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--open-by-default&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Open By Default (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--open-by-default&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Open By Default (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--open-by-default&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Open By Default (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--open-by-default&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Button Text', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--longer-button-text&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Button Text (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--longer-button-text&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Button Text (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--longer-button-text&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Button Text (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--longer-button-text&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Button Text (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--longer-button-text&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Button Text (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--longer-button-text&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Lists', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--longer-lists&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Lists (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--longer-lists&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Lists (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--longer-lists&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Lists (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--longer-lists&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Lists (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--longer-lists&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer Lists (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--longer-lists&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer lists (open)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--longer-lists-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer lists (open) (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--longer-lists-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer lists (open) (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--longer-lists-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer lists (open) (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--longer-lists-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer lists (open) (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--longer-lists-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Longer lists (open) (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--longer-lists-open&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Menu alignment (end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(2000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Menu alignment (end) (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(2000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Menu alignment (end) (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(2000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Menu alignment (end) (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(2000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Menu alignment (end) (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(2000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Menu alignment (end) (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--menu-alignment&viewMode=story',
    )

    await page.waitForTimeout(2000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Menu', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--disabled-menu&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Menu (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--disabled-menu&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Menu (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--disabled-menu&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Menu (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--disabled-menu&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Menu (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--disabled-menu&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Menu (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--disabled-menu&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--anchored-positioning&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--anchored-positioning&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--anchored-positioning&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--anchored-positioning&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--anchored-positioning&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--anchored-positioning&viewMode=story',
    )

    await page.waitForTimeout(1500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning Overrides', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--anchored-positioning-overrides&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning Overrides (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--anchored-positioning-overrides&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning Overrides (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--anchored-positioning-overrides&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning Overrides (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--anchored-positioning-overrides&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning Overrides (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--anchored-positioning-overrides&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Anchored Positioning Overrides (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--anchored-positioning-overrides&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Item', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-actionmenu-features--disabled-item&viewMode=story',
    )

    await page.waitForTimeout(1000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Item (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-actionmenu-features--disabled-item&viewMode=story',
    )

    await page.waitForTimeout(1000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Item (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-actionmenu-features--disabled-item&viewMode=story',
    )

    await page.waitForTimeout(1000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Item (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-actionmenu-features--disabled-item&viewMode=story',
    )

    await page.waitForTimeout(1000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Item (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-actionmenu-features--disabled-item&viewMode=story',
    )

    await page.waitForTimeout(1000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ActionMenu / Disabled Item (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-actionmenu-features--disabled-item&viewMode=story',
    )

    await page.waitForTimeout(1000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })
})
