/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: Card', () => {
  test('Card / Link Text', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-card-features--link-text&viewMode=story')

    expect(await page.screenshot()).toMatchSnapshot()
  })

  test('Card / Label', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-card-features--label&viewMode=story')

    expect(await page.screenshot()).toMatchSnapshot()
  })

  test('Card / Stacked', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-card-features--stacked&viewMode=story')

    expect(await page.screenshot()).toMatchSnapshot()
  })

  test('Card / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-card--default&viewMode=story')

    expect(await page.screenshot()).toMatchSnapshot()
  })
})
