/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: IconButton', () => {
  test('IconButton / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-iconbutton--default&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Playground', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-iconbutton--playground&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / GitHub Toolbar', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-examples--git-hub-toolbar&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for GitHub Toolbar (narrow viewport)', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('IconButton / GitHub Toolbar (narrow viewport)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-iconbutton-examples--git-hub-toolbar-narrow&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })
  test('IconButton / Related formatting actions', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-examples--related-formatting-actions&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Download With Progress', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-examples--download-with-progress&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Download PDF dialog', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-examples--download-pdf-dialog&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Variants', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--variants&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Danger', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--danger&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Sizes', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--sizes&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Rounded', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--rounded&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Kitchen Sink', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--kitchen-sink&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Rounded Kitchen Sink', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--rounded-kitchen-sink&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Control Height Comparison', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--control-height-comparison&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Disabled', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--disabled&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Inactive', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--inactive&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Loading', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--loading&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Loading Interactive', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--loading-interactive&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / With Description', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--with-description&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Button As Link', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--button-as-link&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / With External Tooltip', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--with-external-tooltip&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Long Delayed Tooltip', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--long-delayed-tooltip&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / With Dialog', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--with-dialog&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Focus', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--focus&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Hover', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--hover&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Tooltip Directions', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--tooltip-directions&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('IconButton / Dark Mode', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-iconbutton-features--dark-mode&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
