/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: Accordion', () => {
  test('Accordion / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-accordion--default&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Composition', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--composition&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Toggle Colors', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--toggle-colors&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Always Exactly One Panel Open', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--always-exactly-one-panel-open&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Variant: Emphasis', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--variant-emphasis&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Variant: Emphasis with nested accordions', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--variant-emphasis-with-nested-accordions&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Exclusive Using Name Attribute', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--exclusive-using-name-attribute&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Accordion / Exclusive Without Using Name Attribute', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-accordion-features--exclusive-without-using-name-attribute&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
