declare const styles: {
  readonly "Accordion": string;
  readonly "Accordion--default": string;
  readonly "Accordion--emphasis": string;
  readonly "Accordion__content": string;
  readonly "Accordion__summary": string;
  readonly "Accordion__summary--collapsed": string;
  readonly "Accordion__summary--default": string;
  readonly "Accordion__summary--emphasis": string;
  readonly "Accordion__summary--expanded": string;
  readonly "Accordion__summary--reversed-toggles": string;
  readonly "Accordion__summary--toggleColor-blue": string;
  readonly "Accordion__summary--toggleColor-blue-purple": string;
  readonly "Accordion__summary--toggleColor-coral": string;
  readonly "Accordion__summary--toggleColor-default": string;
  readonly "Accordion__summary--toggleColor-gray": string;
  readonly "Accordion__summary--toggleColor-green": string;
  readonly "Accordion__summary--toggleColor-green-blue": string;
  readonly "Accordion__summary--toggleColor-indigo": string;
  readonly "Accordion__summary--toggleColor-lemon": string;
  readonly "Accordion__summary--toggleColor-lime": string;
  readonly "Accordion__summary--toggleColor-orange": string;
  readonly "Accordion__summary--toggleColor-pink": string;
  readonly "Accordion__summary--toggleColor-pink-blue": string;
  readonly "Accordion__summary--toggleColor-purple": string;
  readonly "Accordion__summary--toggleColor-purple-red": string;
  readonly "Accordion__summary--toggleColor-red": string;
  readonly "Accordion__summary--toggleColor-red-orange": string;
  readonly "Accordion__summary--toggleColor-teal": string;
  readonly "Accordion__summary--toggleColor-yellow": string;
  readonly "fade-in": string;
};
export = styles;

