#!/bin/bash
set -e

# Add base url to be able to serve static files
if [ -n "$1" ]; then
  echo "Building storybook for preview"
  echo '<base href="/storybook/" />' >> .storybook/manager-head.html
else
  echo "Building storybook for production"
  echo '<base href="/brand/storybook/" />' >> .storybook/manager-head.html
fi

mkdir -p ../../apps/docs/public/storybook
# Build storybook inside docs
../../node_modules/.bin/build-storybook -o ../../apps/docs/public/storybook -s ../../apps/docs/public/static

# Remove manager-head after build to not interfere with dev builds
rm .storybook/manager-head.html
