#!/bin/bash
set -e

# Add base url to be able to serve static files
echo '<base href="/brand/storybook/" />' >> .storybook/manager-head.html

mkdir -p ../../apps/docs/public/storybook
# Build storybook inside docs
npx storybook build -o ../../apps/docs/public/storybook

# Remove manager-head after build to not interfere with dev builds
rm .storybook/manager-head.html
