#!/bin/bash
set -e

# Add base url to be able to serve static files
if [ -n "$1" ]; then
  echo "Building storybook for preview"
  echo '<base href="/storybook/" />' >> .storybook/manager-head.html
else
  echo "Building storybook for production"
  echo '<base href="/brand/storybook/" />' >> .storybook/manager-head.html
fi

OUT_DIR="../../apps/docs/public/storybook"
mkdir -p "$OUT_DIR"

STATIC_DIR="../../apps/docs/public/static"
mkdir -p "$STATIC_DIR"

# Build storybook inside docs
npx storybook build -o "$OUT_DIR" -s "$STATIC_DIR"

# Remove manager-head after build to not interfere with dev builds
rm .storybook/manager-head.html
