declare const styles: {
  readonly "VideoPlayer__srOnly": string;
  readonly "VideoPlayer__container": string;
  readonly "VideoPlayer": string;
  readonly "VideoPlayer__playButton": string;
  readonly "VideoPlayer__playButtonInner": string;
  readonly "VideoPlayer__title": string;
  readonly "VideoPlayer__showOverlays": string;
  readonly "VideoPlayer__overlays": string;
  readonly "VideoPlayer__controls": string;
  readonly "VideoPlayer__controlsWrapper": string;
  readonly "VideoPlayer__breakpointSmall": string;
  readonly "VideoPlayer__iconControl": string;
  readonly "VideoPlayer__tooltip": string;
  readonly "VideoPlayer__progressTime": string;
  readonly "VideoPlayer__totalTime": string;
  readonly "VideoPlayer__progressBar2": string;
  readonly "VideoPlayer__closedCaption": string;
  readonly "VideoPlayer__ccOff": string;
  readonly "VideoPlayer__ccText": string;
  readonly "VideoPlayer__range": string;
  readonly "VideoPlayer__volumeBar": string;
  readonly "VideoPlayer__rangeInput": string;
  readonly "VideoPlayer__rangeProgress": string;
  readonly "VideoPlayer__tooltipContent": string;
  readonly "VideoPlayer__tooltipText": string;
  readonly "VideoPlayer__controlTextColor": string;
  readonly "VideoPlayer__shiftTooltipRight": string;
  readonly "VideoPlayer__captions": string;
  readonly "VideoPlayer__captions__empty": string;
  readonly "VideoPlayer__captions__text": string;
};
export = styles;

