declare const styles: {
  readonly "VideoPlayer__container": string;
  readonly "VideoPlayer": string;
  readonly "VideoPlayer__playButtonOverlay": string;
  readonly "VideoPlayer__playButtonOverlay--transparent": string;
  readonly "VideoPlayer__playButton": string;
  readonly "VideoPlayer__title": string;
  readonly "VideoPlayer__controls": string;
  readonly "VideoPlayer__controls--hidden": string;
  readonly "VideoPlayer__controlsBar": string;
  readonly "VideoPlayer__iconControl": string;
  readonly "VideoPlayer__tooltip": string;
  readonly "VideoPlayer__seek": string;
  readonly "VideoPlayer__progressTime": string;
  readonly "VideoPlayer__container--small": string;
  readonly "VideoPlayer__totalTime": string;
  readonly "VideoPlayer__progressBar": string;
  readonly "VideoPlayer__closedCaption": string;
  readonly "VideoPlayer__ccOff": string;
  readonly "VideoPlayer__ccText": string;
  readonly "VideoPlayer__range": string;
  readonly "VideoPlayer__rangeInput": string;
  readonly "VideoPlayer__rangeProgress": string;
  readonly "VideoPlayer__tooltipContent": string;
  readonly "VideoPlayer__tooltipText": string;
  readonly "VideoPlayer__controlTextColor": string;
  readonly "VideoPlayer__seekTime": string;
};
export = styles;

