/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: FeaturePreviewLevelTwo', () => {
  test('FeaturePreviewLevelTwo / Playground', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-feature-previews-level-2--level-two-playground&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Playground (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=recipes-feature-previews-level-2--level-two-playground&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Playground (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=recipes-feature-previews-level-2--level-two-playground&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Playground (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=recipes-feature-previews-level-2--level-two-playground&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Playground (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=recipes-feature-previews-level-2--level-two-playground&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Playground (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=recipes-feature-previews-level-2--level-two-playground&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Minimal', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-feature-previews-level-2--level-two-minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Minimal (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=recipes-feature-previews-level-2--level-two-minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Minimal (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=recipes-feature-previews-level-2--level-two-minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Minimal (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=recipes-feature-previews-level-2--level-two-minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Minimal (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=recipes-feature-previews-level-2--level-two-minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / Minimal (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=recipes-feature-previews-level-2--level-two-minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.1 variant', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-feature-previews-level-2--level-two-point-one&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.1 variant (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=recipes-feature-previews-level-2--level-two-point-one&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.1 variant (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=recipes-feature-previews-level-2--level-two-point-one&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.1 variant (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=recipes-feature-previews-level-2--level-two-point-one&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.1 variant (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=recipes-feature-previews-level-2--level-two-point-one&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.1 variant (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=recipes-feature-previews-level-2--level-two-point-one&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.2 variant', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-feature-previews-level-2--level-two-point-two&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.2 variant (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=recipes-feature-previews-level-2--level-two-point-two&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.2 variant (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=recipes-feature-previews-level-2--level-two-point-two&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.2 variant (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=recipes-feature-previews-level-2--level-two-point-two&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.2 variant (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=recipes-feature-previews-level-2--level-two-point-two&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.2 variant (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=recipes-feature-previews-level-2--level-two-point-two&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.3 variant', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-feature-previews-level-2--level-two-point-three&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.3 variant (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=recipes-feature-previews-level-2--level-two-point-three&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.3 variant (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=recipes-feature-previews-level-2--level-two-point-three&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.3 variant (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=recipes-feature-previews-level-2--level-two-point-three&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.3 variant (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=recipes-feature-previews-level-2--level-two-point-three&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.3 variant (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=recipes-feature-previews-level-2--level-two-point-three&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.4 variant', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-feature-previews-level-2--level-two-point-four&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.4 variant (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=recipes-feature-previews-level-2--level-two-point-four&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.4 variant (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=recipes-feature-previews-level-2--level-two-point-four&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.4 variant (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=recipes-feature-previews-level-2--level-two-point-four&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.4 variant (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=recipes-feature-previews-level-2--level-two-point-four&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('FeaturePreviewLevelTwo / 2.4 variant (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=recipes-feature-previews-level-2--level-two-point-four&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })
})
