#!/bin/bash
set -e

if [ -n "$1" ]; then
  pwd
  npm run build:preview && cd ../storybook && scripts/build-storybook preview
  
else
  npm run build && cd ../storybook && scripts/build-storybook
fi



