/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: Pagination', () => {
  test('Pagination / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-pagination--default&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Pagination / Playground', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-pagination--playground&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Pagination / Larger Page Count Margin', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-pagination-features--larger-page-count-margin&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Pagination / Hide Page Numbers', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-pagination-features--hide-page-numbers&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Narrow Page Numbers Hidden By Default', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('Pagination / Narrow Page Numbers Hidden By Default', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-pagination-features--narrow-page-numbers-hidden-by-default&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })
  test('Pagination / Higher Surrounding Page Count', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-pagination-features--higher-surrounding-page-count&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Pagination / Page Handlers', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-pagination-features--page-handlers&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Pagination / Custom Attribute Forwarding', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-pagination-features--custom-attribute-forwarding&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
