/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: examples', () => {
  test('examples / Agents', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=recipes-flextemplate-examples--agents&viewMode=story')

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('examples / Copilot Business', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-flextemplate-examples--copilot-business&viewMode=story',
    )

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
