/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: Testimonial', () => {
  test('Testimonial / Playground', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-testimonial--playground&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / With Frosted Glass', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-testimonial-examples--with-frosted-glass&viewMode=story',
    )

    await page.waitForTimeout(4000)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Duo', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-testimonial-examples--duo&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Trio', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-testimonial-examples--trio&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Avatar', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-testimonial-features--avatar&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Colored Quote Mark', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-testimonial-features--colored-quote-mark&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Large', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-testimonial-features--large&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Large Highlighted Portion', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-testimonial-features--large-highlighted-portion&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('Testimonial / Testimonial Variants', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-testimonial-features--testimonial-variants&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })
})
