declare const styles: {
  readonly "Testimonial": string;
  readonly "Testimonial__quoteMark": string;
  readonly "Testimonial--center": string;
  readonly "Testimonial--size-large": string;
  readonly "Testimonial-quote": string;
  readonly "Testimonial-quote--muted": string;
  readonly "Testimonial-from": string;
  readonly "Testimonial-logo-image": string;
  readonly "Testimonial__quoteMark--default": string;
  readonly "Testimonial__quoteMark--blue": string;
  readonly "Testimonial__quoteMark--blue-purple": string;
  readonly "Testimonial__quoteMark--coral": string;
  readonly "Testimonial__quoteMark--green": string;
  readonly "Testimonial__quoteMark--green-blue": string;
  readonly "Testimonial__quoteMark--gray": string;
  readonly "Testimonial__quoteMark--indigo": string;
  readonly "Testimonial__quoteMark--lemon": string;
  readonly "Testimonial__quoteMark--lime": string;
  readonly "Testimonial__quoteMark--orange": string;
  readonly "Testimonial__quoteMark--pink": string;
  readonly "Testimonial__quoteMark--pink-blue": string;
  readonly "Testimonial__quoteMark--purple": string;
  readonly "Testimonial__quoteMark--purple-red": string;
  readonly "Testimonial__quoteMark--red": string;
  readonly "Testimonial__quoteMark--red-orange": string;
  readonly "Testimonial__quoteMark--teal": string;
  readonly "Testimonial__quoteMark--yellow": string;
};
export = styles;

