declare const styles: {
  readonly "Label": string;
  readonly "Label--color-blue": string;
  readonly "Label--color-blue-purple": string;
  readonly "Label--color-coral": string;
  readonly "Label--color-default": string;
  readonly "Label--color-gray": string;
  readonly "Label--color-green": string;
  readonly "Label--color-green-blue": string;
  readonly "Label--color-green-blue-purple": string;
  readonly "Label--color-indigo": string;
  readonly "Label--color-lemon": string;
  readonly "Label--color-lime": string;
  readonly "Label--color-orange": string;
  readonly "Label--color-pink": string;
  readonly "Label--color-pink-blue": string;
  readonly "Label--color-purple": string;
  readonly "Label--color-purple-red": string;
  readonly "Label--color-red": string;
  readonly "Label--color-red-orange": string;
  readonly "Label--color-teal": string;
  readonly "Label--color-yellow": string;
  readonly "Label--gradient": string;
  readonly "Label--size-large": string;
  readonly "Label--size-medium": string;
  readonly "Label__icon-visual": string;
  readonly "Label__label": string;
  readonly "Label__leading-visual": string;
  readonly "Label__text": string;
};
export = styles;

