/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: SubdomainNavBar', () => {
  test('SubdomainNavBar / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar--default&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Playground', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar--playground&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / No Search', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--no-search&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Search Open', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--search-open&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(5500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Search Results Visible', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--search-results-visible&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(5500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Search Keyboard Shortcut', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--search-keyboard-shortcut&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Search Custom Keyboard Shortcut', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--search-custom-keyboard-shortcut&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Grouped Search Results Visible', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--grouped-search-results-visible&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Overflow Menu Open', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--overflow-menu-open&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(1500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Desktop Pill States', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--desktop-pill-states&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Tablet viewport test for Tablet View', () => {
    test.use({viewport: {width: 834, height: 1112}})
    test('SubdomainNavBar / Tablet View', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--tablet-view&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Tablet viewport test for Tablet Menu Open', () => {
    test.use({viewport: {width: 834, height: 1112}})
    test('SubdomainNavBar / Tablet Menu Open', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--tablet-menu-open&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile View', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Mobile View', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--mobile-view&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile Menu Open', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Mobile Menu Open', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--mobile-menu-open&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile Menu Open Many Items', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Mobile Menu Open Many Items', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--mobile-menu-open-many-items&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile Search Results Visible', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Mobile Search Results Visible', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--mobile-search-results-visible&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile No Links', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Mobile No Links', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--mobile-no-links&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile Leading Component Only Menu Open', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Mobile Leading Component Only Menu Open', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--mobile-leading-component-only-menu-open&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })
  test('SubdomainNavBar / No overflow menu (1 link)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--no-overflow&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Longer Title', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--longer-title&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(1500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Full Width', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--full-width&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / With Leading Component', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--with-leading-component&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / With Trailing Component', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--with-trailing-component&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / No Title', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--no-title&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / External Link', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--external-link&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Reversed Button Order', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--reversed-button-order&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Reversed Button Order Narrow', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('SubdomainNavBar / Reversed Button Order Narrow', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--reversed-button-order-narrow&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(5500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })
  test('SubdomainNavBar / Imperative Search API', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--imperative-search-api&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Conditional Rendering', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--conditional-rendering&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Skip To Main Tag', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--skip-to-main-tag&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('SubdomainNavBar / Skip To Main Tag With Id', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-subdomainnavbar-features--skip-to-main-tag-with-id&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
