/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: CategoryPage', () => {
  test('CategoryPage / Light', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=recipes-solutions-categorypage--light&viewMode=story')

    await page.waitForTimeout(4000)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('CategoryPage / Dark', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=recipes-solutions-categorypage--dark&viewMode=story')

    await page.waitForTimeout(4000)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
