import {makeContext} from '../../test-utils/catalog.js'
import {primerPageDesignTool} from './primer-brand-page-design.js'

describe('primer_brand_page_design', () => {
  it('returns the bundled page-design guidance', async () => {
    const result = await primerPageDesignTool.run({}, makeContext())
    expect(result.isError).toBeFalsy()
    expect(result.text).toContain('SubdomainNavBar')
    expect(result.text).toContain('gridline')
    expect(result.text).toContain('FlexSuiteAIOverview')
    expect(result.text).toContain('<River variant="gridline" align="start">')
    expect(result.text).toContain('Keep River descriptions to a maximum of 160 characters')
    expect(result.text).toContain('Prefer the default `50:50` image-to-text ratio')
    expect(result.text).toContain('imageTextRatio="60:40"')
    expect(result.text).toContain('Always pair dither with product UI')
    expect(result.text).toContain('Use two separate layers for every product UI visual')
    expect(result.text).toContain('Treat a solid subtle/gray surround as placeholder-only')
    expect(result.text).toContain('Replace the entire surrounding surface with dither')
    expect(result.text).toContain('proactively create one lightweight, representative product UI mockup')
    expect(result.text).toContain('show that product imagery matters')
    expect(result.text).toContain('user should replace it with their own screenshot')
    expect(result.text).not.toContain('page budget')
    expect(result.text).not.toContain('time remains')
    expect(result.text).not.toContain('first successful build')
    expect(result.text).toContain('Every Hero must include relevant visual media')
    expect(result.text).toContain('Do not render product UI directly through `Hero.Image`')
    expect(result.text).toContain('two-layer treatment in **Generated dither backgrounds**')
    expect(result.text).toContain('A missing input screenshot is not a reason to omit Hero media')
    expect(result.text).toContain('text and actions only because the brief did not provide an image')
    expect(result.text).toContain('Never pass dither to `Hero.Image`')
    expect(result.text).toContain('direct image child of `River.Visual`')
    expect(result.text).toContain('dither wrapper span the full viewport width')
    expect(result.text).toContain('dither wrapper fill the `River.Visual` cell')
    expect(result.text).toContain('wallpaper-only product Rivers read as placeholders')
    expect(result.text).toContain('`Pillar` has no grid variant')
    expect(result.text).toContain('### Hero')
    expect(result.text).toContain('### River')
    expect(result.text).toContain('**Do**')
    expect(result.text).toContain("**Don't**")
    expect(result.text).toContain('### Repeated panels')
    expect(result.text).toContain('Never let a border stop in empty space')
    expect(result.text).toContain('block-start and block-end rules the same extent')
    expect(result.text).toContain('`Card`, `Pillar`, `Box`, or custom items')
    expect(result.text).toContain('border-radius: 0')
    expect(result.text).toContain('<CTABanner variant="balanced" hasGridLines>')
    expect(result.text).toContain('multiple meaningful categories')
    expect(result.text).toContain('--base-size-20')
    expect(result.text).toContain('--base-size-60')
    expect(result.text).toContain('--base-size-64')
    expect(result.text).toContain('--base-size-80')
    expect(result.text).toContain('product UI media band immediately after the Hero copy')
    expect(result.text).toContain('dither is the full-bleed media-band background')
    expect(result.text).toContain('product shot is the contained foreground')
    expect(result.text).toContain('not permission to make the product shot itself bleed full-width')
    expect(result.text).toContain('stable aspect ratio')
    expect(result.text).toContain('token-backed maximum height')
    expect(result.text).toContain('place custom media after `Hero`')
    expect(result.text).toContain('use `trailingComponent`')
    expect(result.text).toContain('catches some code-level mistakes automatically')
    expect(result.text).not.toContain('152px')
  })

  it('names the Asset Generator media tools only when it is available', async () => {
    const result = await primerPageDesignTool.run({}, makeContext({assetGenerator: {available: true}}))
    expect(result.text).toContain('asset-generator')
    expect(result.text).toContain('create_dither_patterns')
    expect(result.text).toContain('create_full_screen_product_shot')
    expect(result.text).toContain('create_product_landscape')
  })

  it('never mentions the internal Asset Generator when it is absent', async () => {
    const result = await primerPageDesignTool.run({}, makeContext())
    expect(result.text).not.toContain('asset-generator')
    expect(result.text).not.toContain('create_dither_patterns')
    expect(result.text).not.toContain('create_full_screen_product_shot')
    expect(result.text).not.toContain('create_product_landscape')
    expect(result.text).not.toContain('create_social_square')
  })
})
