import {makeContext} from '../../test-utils/catalog.js'
import {primerPageDesignTool} from './primer-brand-page-design.js'

describe('primer_brand_page_design', () => {
  it('returns the bundled page-design guidance', async () => {
    const result = await primerPageDesignTool.run({}, makeContext())
    expect(result.isError).toBeFalsy()
    expect(result.text).toContain('SubdomainNavBar')
    expect(result.text).toContain('gridline')
    expect(result.text).toContain('FlexSuiteAIOverview')
    expect(result.text).toContain('<River variant="gridline" align="start">')
    expect(result.text).toContain('`Pillar` has no grid variant')
    expect(result.text).toContain('### Do')
    expect(result.text).toContain("### Don't")
    expect(result.text).toContain('**Repeated panels**')
    expect(result.text).toContain('`Card`, `Pillar`, `Box`, or custom items')
    expect(result.text).toContain('border-radius: 0')
    expect(result.text).toContain('<CTABanner variant="balanced" hasGridLines>')
    expect(result.text).toContain('multiple meaningful categories')
    expect(result.text).toContain('--base-size-20')
    expect(result.text).toContain('--base-size-60')
    expect(result.text).toContain('--base-size-64')
    expect(result.text).toContain('--base-size-80')
    expect(result.text).toContain('create_product_landscape')
    expect(result.text).toContain('create_wallpaper')
    expect(result.text).toContain('stable aspect ratio')
    expect(result.text).toContain('token-backed maximum height')
    expect(result.text).toContain('place custom media after `Hero`')
    expect(result.text).toContain('use `trailingComponent`')
    expect(result.text).toContain('catches some code-level mistakes automatically')
    expect(result.text).not.toContain('152px')
  })
})
