/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: Industry', () => {
  test('Industry / Maximum Light', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-solutions-solution-industry--maximum&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(3500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Industry / Maximum Dark', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-solutions-solution-industry--maximum-dark&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(3500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Industry / Minimum Light', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-solutions-solution-industry--minimum&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(3500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('Industry / Minimum Dark', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=recipes-solutions-solution-industry--minimum-dark&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(3500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
