#!/bin/bash

echo 'Benchmarking $PWD...'

# Add base url to be able to serve static files
echo '<base href="/react-brand/storybook/" />' >> .storybook/manager-head.html

# Build storybook inside docs
./node_modules/.bin/build-storybook -o docs/public/storybook -s docs/public/static

# Remove manager-head after build to not interfere with dev builds
rm .storybook/manager-head.html
