#!/bin/bash
set -e

if [ -n "$1" ]; then
  echo 'running preview mode'
  cd docs && npm run build:preview && cd ../ && npm run build:storybook
else
  echo 'running production mode'
  cd docs && npm run build && cd ../ && npm run build:storybook
fi



