/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: FeatureComparisonTable', () => {
  test('FeatureComparisonTable / Default', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable--default&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Playground', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable--playground&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Copilot Individual Plans', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-examples--copilot-individual-plans&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Two Plans', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--two-plans&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Three Plans', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--three-plans&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Featured First Plan', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--featured-first-plan&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Featured Last Plan', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--featured-last-plan&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Four Plans', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--four-plans&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Feature Rows', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--feature-rows&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Plan Summaries', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--plan-summaries&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Mobile Viewport', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('FeatureComparisonTable / Mobile Viewport', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--mobile-viewport&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Tablet viewport test for Tablet Viewport', () => {
    test.use({viewport: {width: 834, height: 1112}})
    test('FeatureComparisonTable / Tablet Viewport', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--tablet-viewport&viewMode=story',
        {waitUntil: 'networkidle'},
      )
      await page.locator('body.sb-show-main').waitFor({state: 'visible'})

      await page.waitForTimeout(500)
      await expect(page).toHaveScreenshot({fullPage: true})
    })
  })
  test('FeatureComparisonTable / Collapsed Groups', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--collapsed-groups&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Responsive Group Expansion', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--responsive-group-expansion&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Sticky Headers', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--sticky-headers&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Dark Mode', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--dark-mode&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('FeatureComparisonTable / Row Highlighting', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-featurecomparisontable-features--row-highlighting&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
