/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: TextRevealAnimation', () => {
  test('TextRevealAnimation / Playground', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-textrevealanimation--playground&viewMode=story',
    )

    await page.waitForTimeout(3000)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('TextRevealAnimation / With Large Testimonial', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-textrevealanimation-examples--with-large-testimonial&viewMode=story',
    )

    await page.waitForTimeout(3000)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('TextRevealAnimation / With Hero', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-textrevealanimation-examples--with-hero&viewMode=story',
    )

    await page.waitForTimeout(3000)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('TextRevealAnimation / Animation On Scroll', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-textrevealanimation-features--animation-on-scroll&viewMode=story',
    )

    await page.waitForTimeout(3000)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
