/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: ToggleSwitch', () => {
  test('ToggleSwitch / Default', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch--default&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Playground', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch--playground&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Settings Panel', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-examples--settings-panel&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Optimistic Update', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-examples--optimistic-update&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Optimistic Update Failure', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-examples--optimistic-update-failure&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / With Form Control', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--with-form-control&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Checked', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--checked&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Disabled', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--disabled&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Sizes', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--sizes&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Control Height Comparison', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--control-height-comparison&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Dark', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--dark&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Controlled', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--controlled&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Loading With Form Controls', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--loading-with-form-controls&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Standalone Loading Positions', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--standalone-loading-positions&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Validation', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--validation&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / External Label', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--external-label&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Visually Hidden Label', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--visually-hidden-label&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Long Label', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--long-label&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Right To Left', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--right-to-left&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('ToggleSwitch / Focus', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-forms-toggleswitch-features--focus&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
