/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: River', () => {
  test('River / Default', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river--default&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Larger Placeholder Image', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river--larger-placeholder-image&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Copilot', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river--copilot&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Custom background (start)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-examples--custom-background-start&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Custom background (end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-examples--custom-background-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Custom background (start, video)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-examples--custom-background-start-video&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Left', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river-features--left&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Right', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river-features--right&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Center', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river-features--center&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Duo Tone', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river-features--duo-tone&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / 60:40 image ratio', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--column-ratio-6040&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / 50:50 image ratio', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--column-ratio-5050&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Alternative Heading Level', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--alternative-heading-level&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / No Rounded Visual Corners', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--no-rounded-visual-corners&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Alternative Heading Size', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--alternative-heading-size&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / With Label', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-river-features--with-label&viewMode=story', {
      waitUntil: 'networkidle',
    })
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Custom trailing content', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--custom-trailing-content&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Custom trailing content w/ divider', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--custom-trailing-content-with-divider&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Alternating Layout', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--alternating-layout&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / Content align block-end', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features--content-align-block-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (centered)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-center&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (with background)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-with-background&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (with background, end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-with-background-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (with background, centered)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-with-background-center&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (with EyebrowText)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-with-eyebrow-text&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (with Label)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-with-label&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (content align block-end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-content-align-block-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (60:40)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-6040&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (60:40, end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-6040-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (60:40, centered)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-6040-center&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (60:40, with background)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-6040-with-background&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (60:40, with background, end)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-6040-with-background-end&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })

  test('River / GridLine variant (60:40, with background, centered)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?args=&id=components-river-features-gridline-variants--grid-line-6040-with-background-center&viewMode=story',
      {waitUntil: 'networkidle'},
    )
    await page.locator('body.sb-show-main').waitFor({state: 'visible'})

    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot({fullPage: true})
  })
})
