/*
 * Do not modify this file directly.
 * This file was generated by: playwright.generate-tests.ts.
 * Regenerate using: npm run test:visual:generate
 */
import {test, expect} from '@playwright/test'

// eslint-disable-next-line i18n-text/no-en
test.describe('Visual Comparison: ComparisonTable', () => {
  test('ComparisonTable / Playground', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-comparisontable--playground&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Playground (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-comparisontable--playground&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Playground (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-comparisontable--playground&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Playground (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-comparisontable--playground&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Playground (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-comparisontable--playground&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Playground (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-comparisontable--playground&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  // eslint-disable-next-line i18n-text/no-en
  test.describe('Mobile viewport test for Playground (mobile)', () => {
    test.use({viewport: {width: 360, height: 800}})
    test('ComparisonTable / Playground (mobile)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?args=&id=components-comparisontable--playground-mobile&viewMode=story',
      )

      await page.waitForTimeout(500)
      expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
    })

    test('ComparisonTable / Playground (mobile) (fr)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-comparisontable--playground-mobile&viewMode=story',
      )

      await page.waitForTimeout(500)
      expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
    })

    test('ComparisonTable / Playground (mobile) (de)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-comparisontable--playground-mobile&viewMode=story',
      )

      await page.waitForTimeout(500)
      expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
    })

    test('ComparisonTable / Playground (mobile) (ja)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-comparisontable--playground-mobile&viewMode=story',
      )

      await page.waitForTimeout(500)
      expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
    })

    test('ComparisonTable / Playground (mobile) (es)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-comparisontable--playground-mobile&viewMode=story',
      )

      await page.waitForTimeout(500)
      expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
    })

    test('ComparisonTable / Playground (mobile) (pt-BR)', async ({page}) => {
      await page.goto(
        'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-comparisontable--playground-mobile&viewMode=story',
      )

      await page.waitForTimeout(500)
      expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
    })
  })
  test('ComparisonTable / Minimal', async ({page}) => {
    await page.goto('http://localhost:6006/iframe.html?args=&id=components-comparisontable--minimal&viewMode=story')

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Minimal (fr)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Afr&args=&id=components-comparisontable--minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Minimal (de)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Ade&args=&id=components-comparisontable--minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Minimal (ja)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aja&args=&id=components-comparisontable--minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Minimal (es)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Aes&args=&id=components-comparisontable--minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })

  test('ComparisonTable / Minimal (pt-BR)', async ({page}) => {
    await page.goto(
      'http://localhost:6006/iframe.html?globals=locale%3Apt-BR&args=&id=components-comparisontable--minimal&viewMode=story',
    )

    await page.waitForTimeout(500)
    expect(await page.screenshot({fullPage: true})).toMatchSnapshot()
  })
})
