declare const styles: {
  readonly articleBody: string
  readonly articleColumn: string
  readonly articleGrid: string
  readonly articleHero: string
  readonly bodySection: string
  readonly codeExample: string
  readonly codeExampleAside: string
  readonly codeExampleBody: string
  readonly codeExampleHeader: string
  readonly codeExampleTabSelected: string
  readonly codeExampleTabs: string
  readonly codeLines: string
  readonly contentBlock: string
  readonly headerSection: string
  readonly iconButton: string
  readonly imageFigure: string
  readonly imagePlaceholder: string
  readonly inlineCode: string
  readonly layout: string
  readonly main: string
  readonly proTip: string
  readonly proTipBody: string
  readonly proTipHeader: string
  readonly proTipTitle: string
  readonly relatedArticles: string
  readonly relatedArticlesHeader: string
  readonly relatedCards: string
  readonly secondarySidebar: string
  readonly sectionSpacer: string
  readonly sidebar: string
  readonly step: string
  readonly stepContent: string
  readonly stepList: string
  readonly stepNumber: string
  readonly steps: string
}
export = styles
