name: Update visual snapshots

env:
  NODE_ENV: test
  PINNED_CHROME_VERSION: 146.0.7680.165

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-snapshots:
    if: ${{ github.event.label.name == 'update snapshots' }}
    name: Update snapshots
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Set up pinned Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.PINNED_CHROME_VERSION }}

      - name: Regenerate specs and update snapshots
        run: npm run test:visual:update-snapshots --workspace=packages/e2e
        env:
          PW_CHROME_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: github-actions[bot] Regenerated snapshots
